### ISSUE TITLE
Review - Alan McAdams

### ISSUE THREAD

**Issue by AlanMcAdams** [cmiller112000/ud-datavis#4]
•What do you notice in the visualization?
When filtered by airline, the airline dots (info) disappears from graph and when airline re-clicked it does not reappear. If all airlines are clicked the graph goes blank and stays blank, have to refresh screen to bring back data.

Sometimes after picking a year or airport the visualization starts scrolling again when should stay paused?

•What questions do you have about the data? 
None, really. It is presented clearly

•What relationships do you notice?
Southwest airlines started to take delays seriously in 2005 and has best showing in the list at most destinations in the following years,

•What do you think is the main take-away from this visualization?
Fly Southwest

•Is there something you don’t understand in the graphic?
It is difficult to tell which Airport is being represented in the graph because when you click the airport it stays highlighted even when the next airport is picked.
Maybe graph titles which change with selections picked to show what airport and year is being shown??

Any Additions Comments:
Very interesting!

**Comment by cmiller112000** [comment]
Thanks Alan, good feedback!  I have a new version I will be uploading later today or tomorrow (waiting for feedback from class peers).  This new version fixes the disappearing data issue, and makes the airport filter clearer and easier to read.  I also changed the bubble graph to a line graph with line markers so that the day to day differences are more obvious. I liked the bouncing balls, but it didn't make that relationship very clear.

I haven't figured out how to keep the animation paused when filtering by carrier or airport yet, still working to figure out how to do that.
